# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML5
        cache: true
    redis:
        host: 127.0.0.1
        port: 6379
    mail:
        host:
        port: 587
        username: postmaster@localhost
        password:
        protocol: smtp
        tls: true
        auth: true

security:
    basic:
        enabled: false



# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    mailgun:
        apiUrl: https://xxxxxx/messages
        apiKey: key-xxxxxx
        from: Expper <noreply@mail.expper.com>
    sendcloud:
        url: http://sendcloud.sohu.com/webapi/mail.send.json
        user: expper_sendcloud_user
        key: xxxxxx
        from: noreply@mail.expper.com
        fromName: Expper
    qiniu:
        bucket:
        domain:
        accessKey:
        secretKey:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000

    #cors: #By default CORS are not enabled. Uncomment to enable.
            #allowed-origins: "*"
            #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
            #allowed-headers: "*"
            #exposed-headers:
            #allow-credentials: true
            #max-age: 1800

    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 81878383ea3b04556ac022384979fc4fda2452b5
    swagger:
        title: expper API
        description: expper API documentation
        version: 0.2.5
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
